"""
OMOP CDM 공유 데이터 상수

SchemaLinker / ITMetaService / BizMetaService 공통 참조 데이터.
schema.py에서 분리하여 데이터 정의만 모아둠.
"""

from typing import Dict, List, Tuple


# 의료 도메인 참조 정보 (evidence) - OMOP CDM + SNOMED CT codes (Synthea)
MEDICAL_EVIDENCE: Dict[str, str] = {
    "당뇨": "당뇨병(Diabetes Mellitus)의 SNOMED CT 코드는 44054006입니다. condition_occurrence.condition_source_value = '44054006' 조건을 사용합니다.",
    "고혈압": "고혈압(Hypertension)의 SNOMED CT 코드는 38341003입니다. condition_source_value = '38341003' 조건을 사용합니다.",
    "심방세동": "심방세동(Atrial Fibrillation)의 SNOMED CT 코드는 49436004입니다. condition_source_value = '49436004' 조건을 사용합니다.",
    "심근경색": "심근경색(Myocardial Infarction)의 SNOMED CT 코드는 22298006입니다. condition_source_value = '22298006' 조건을 사용합니다.",
    "뇌졸중": "뇌졸중(Stroke)의 SNOMED CT 코드는 230690007입니다. condition_source_value = '230690007' 조건을 사용합니다.",
    "관상동맥": "관상동맥 질환(Coronary arteriosclerosis)의 SNOMED CT 코드는 53741008입니다. condition_source_value = '53741008' 조건을 사용합니다.",
    "기관지염": "급성 기관지염(Acute bronchitis)의 SNOMED CT 코드는 10509002입니다. condition_source_value = '10509002' 조건을 사용합니다.",
    "인두염": "급성 바이러스성 인두염(Acute viral pharyngitis)의 SNOMED CT 코드는 195662009입니다. condition_source_value = '195662009' 조건을 사용합니다.",
    "남성": "성별 조건: person.gender_source_value = 'M' 또는 person.gender_concept_id = 8507",
    "여성": "성별 조건: person.gender_source_value = 'F' 또는 person.gender_concept_id = 8532",
    "입원": "입원 환자: visit_occurrence.visit_concept_id = 9201",
    "외래": "외래 환자: visit_occurrence.visit_concept_id = 9202",
    "응급": "응급 환자: visit_occurrence.visit_concept_id = 9203",
    "X-ray": "흉부 X-ray 영상: imaging_study 테이블 사용. image_url 컬럼에 이미지 경로 있음. finding_labels로 소견 필터 가능.",
    "영상": "영상 검사: imaging_study 테이블 사용. finding_labels 컬럼에 소견 (Cardiomegaly, Effusion, Pneumonia 등) 저장.",
    "촬영": "영상 촬영: imaging_study 테이블 사용. view_position(PA/AP), patient_age, patient_gender 컬럼 제공.",
    "흉부": "흉부 X-ray: imaging_study 테이블에서 조회. image_url로 이미지 확인 가능.",
    # 영상 소견 한글→영문 매핑 (finding_labels는 반드시 영문으로 검색해야 함)
    "폐렴": "폐렴은 영문 Pneumonia입니다. imaging_study.finding_labels ILIKE '%Pneumonia%' 조건을 사용합니다.",
    "심비대": "심비대는 영문 Cardiomegaly입니다. imaging_study.finding_labels ILIKE '%Cardiomegaly%' 조건을 사용합니다.",
    "흉수": "흉수는 영문 Effusion입니다. imaging_study.finding_labels ILIKE '%Effusion%' 조건을 사용합니다.",
    "폐기종": "폐기종은 영문 Emphysema입니다. imaging_study.finding_labels ILIKE '%Emphysema%' 조건을 사용합니다.",
    "침윤": "침윤은 영문 Infiltration입니다. imaging_study.finding_labels ILIKE '%Infiltration%' 조건을 사용합니다.",
    "무기폐": "무기폐는 영문 Atelectasis입니다. imaging_study.finding_labels ILIKE '%Atelectasis%' 조건을 사용합니다.",
    "기흉": "기흉은 영문 Pneumothorax입니다. imaging_study.finding_labels ILIKE '%Pneumothorax%' 조건을 사용합니다.",
    "종괴": "종괴는 영문 Mass입니다. imaging_study.finding_labels ILIKE '%Mass%' 조건을 사용합니다.",
    "결절": "결절은 영문 Nodule입니다. imaging_study.finding_labels ILIKE '%Nodule%' 조건을 사용합니다.",
    "경화": "경화는 영문 Consolidation입니다. imaging_study.finding_labels ILIKE '%Consolidation%' 조건을 사용합니다.",
    "부종": "부종은 영문 Edema입니다. imaging_study.finding_labels ILIKE '%Edema%' 조건을 사용합니다.",
    "섬유화": "섬유화는 영문 Fibrosis입니다. imaging_study.finding_labels ILIKE '%Fibrosis%' 조건을 사용합니다.",
    "탈장": "탈장은 영문 Hernia입니다. imaging_study.finding_labels ILIKE '%Hernia%' 조건을 사용합니다.",
    "흉막비후": "흉막비후는 영문 Pleural_Thickening입니다. imaging_study.finding_labels ILIKE '%Pleural_Thickening%' 조건을 사용합니다.",
    "소견": "imaging_study.finding_labels 컬럼은 영문(Cardiomegaly, Effusion, Pneumonia 등)으로 저장됩니다. 소견 유형별 분포: SELECT finding_labels, COUNT(*) AS cnt FROM imaging_study GROUP BY finding_labels ORDER BY cnt DESC. 전체 건수 포함 시 SUM(COUNT(*)) OVER() AS total 사용. 한글 소견명은 반드시 영문으로 변환하여 검색하세요.",
    # 비용 관련
    "비용": "의료 비용: cost 테이블 사용. cost 컬럼(DOUBLE PRECISION)에 금액. person_person_id로 환자 JOIN. incurred_date=발생일, paid_date=지급일.",
    "진료비": "진료비: cost 테이블의 cost 컬럼. cost.person_person_id = person.person_id로 환자별 비용 합산 가능.",
    "의료비": "의료비: cost 테이블(4,426,770건). cost.person_person_id로 환자 JOIN, cost.payer_plan_period_payer_plan_period_id로 보험 JOIN.",
    # 보험 관련
    "보험": "보험 정보: payer_plan_period 테이블. payer_source_value=보험사, plan_source_value=보험플랜. contract_person_id 또는 person_person_id로 환자 JOIN.",
    "보험사": "보험사: payer_plan_period.payer_source_value에 보험사명 저장.",
    # 진단기간/약물기간 관련
    "진단기간": "진단 기간: condition_era 테이블. condition_occurrence를 집계한 연속 진단 기간. condition_occurrence_count=발생횟수.",
    "약물기간": "약물 투여 기간: drug_era 테이블. drug_exposure를 집계한 연속 투여 기간. drug_exposure_count=처방횟수, gap_days=중단일수.",
    "투여기간": "투여 기간: drug_era 테이블 사용. drug_era_start_date~drug_era_end_date.",
    # 의료기기 관련
    "기기": "의료기기: device_exposure 테이블. device_source_value에 기기코드, quantity에 수량. person_person_id로 환자 JOIN.",
    "의료기기": "의료기기: device_exposure 테이블(432,867건). person_person_id로 환자 JOIN, visit_occurrence_visit_occurrence_id로 방문 JOIN.",
    "장치": "의료 장치: device_exposure 테이블. device_source_value에 장치 코드.",
    # 관찰기간 관련
    "관찰기간": "관찰 기간: observation_period 테이블. 환자별 데이터 수집 기간을 나타냄. observation_period_start_date~observation_period_end_date.",
    # 방문상세
    "방문상세": "방문 상세: visit_detail 테이블. visit_occurrence의 하위 방문 기록. provider_id=담당의, care_site_id=진료소.",
    # 의료진/진료소/위치
    "의사": "의료진: provider 테이블. provider_name=이름, specialty_source_value=전문분야, npi=국가제공자식별번호.",
    "의료진": "의료진: provider 테이블(905,492건). care_site_care_site_id로 소속 진료소 JOIN.",
    "전문과": "전문 분야: provider.specialty_source_value에 전문과목 저장.",
    "진료소": "진료소: care_site 테이블(7,100건). care_site_name=진료소명, location_location_id로 위치 JOIN.",
    "진료과": "진료과: care_site 테이블. care_site_name 또는 care_site_source_value로 진료과 조회.",
    "부서": "부서: care_site 테이블에서 care_site_name으로 부서명 조회.",
    "위치": "위치: location 테이블. city=도시, state=주/도, zip=우편번호, county=군/구, latitude/longitude=위경도.",
    "주소": "주소: location 테이블. city, state, zip, county 컬럼으로 주소 조합.",
    "DRG": "DRG 코드: cost.drg_source_value에 DRG 원본 코드 저장.",
}


# =============================================================================
# OMOP CDM 테이블 메타데이터 (Synthea 합성 데이터)
# =============================================================================

SAMPLE_TABLES: List[Dict] = [
    {
        "physical_name": "person",
        "business_name": "환자",
        "description": "환자 기본 정보 (1,130명). gender_source_value로 성별(M/F) 조회.",
        "domain": "환자",
        "columns": [
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "환자 고유 ID"},
            {"physical_name": "gender_concept_id", "business_name": "성별개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "8507: 남성, 8532: 여성"},
            {"physical_name": "year_of_birth", "business_name": "출생연도", "data_type": "INTEGER", "is_pk": False, "is_nullable": True, "description": "출생 연도"},
            {"physical_name": "month_of_birth", "business_name": "출생월", "data_type": "INTEGER", "is_pk": False, "is_nullable": True, "description": "출생 월"},
            {"physical_name": "day_of_birth", "business_name": "출생일", "data_type": "INTEGER", "is_pk": False, "is_nullable": True, "description": "출생 일"},
            {"physical_name": "birth_datetime", "business_name": "출생일시", "data_type": "TIMESTAMP", "is_pk": False, "is_nullable": True, "description": "출생 일시"},
            {"physical_name": "race_concept_id", "business_name": "인종개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "인종 개념 ID"},
            {"physical_name": "ethnicity_concept_id", "business_name": "민족개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "민족 개념 ID"},
            {"physical_name": "person_source_value", "business_name": "원본환자번호", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "원본 환자번호"},
            {"physical_name": "gender_source_value", "business_name": "성별", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "성별 원본값 (M/F)"},
        ],
    },
    {
        "physical_name": "condition_occurrence",
        "business_name": "진단기록",
        "description": "환자 진단/질환 기록 (7,900건). condition_source_value에 SNOMED CT 코드 저장.",
        "domain": "진료",
        "columns": [
            {"physical_name": "condition_occurrence_id", "business_name": "진단기록ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "진단 기록 고유 ID"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "환자 ID (FK → person)"},
            {"physical_name": "condition_concept_id", "business_name": "진단개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "진단 SNOMED 개념 ID"},
            {"physical_name": "condition_start_date", "business_name": "진단시작일", "data_type": "DATE", "is_pk": False, "is_nullable": False, "description": "진단 시작일"},
            {"physical_name": "condition_end_date", "business_name": "진단종료일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "진단 종료일"},
            {"physical_name": "condition_source_value", "business_name": "진단원본코드", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "SNOMED CT 코드 (예: 44054006=당뇨, 38341003=고혈압)"},
            {"physical_name": "visit_occurrence_id", "business_name": "방문ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "방문 ID (FK → visit_occurrence)"},
        ],
    },
    {
        "physical_name": "visit_occurrence",
        "business_name": "방문기록",
        "description": "환자 방문(입원/외래/응급) 기록 (32,153건). visit_concept_id로 방문 유형 구분.",
        "domain": "진료",
        "columns": [
            {"physical_name": "visit_occurrence_id", "business_name": "방문기록ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "방문 기록 고유 ID"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "환자 ID (FK → person)"},
            {"physical_name": "visit_concept_id", "business_name": "방문유형ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "9201: 입원, 9202: 외래, 9203: 응급"},
            {"physical_name": "visit_start_date", "business_name": "방문시작일", "data_type": "DATE", "is_pk": False, "is_nullable": False, "description": "방문 시작일"},
            {"physical_name": "visit_end_date", "business_name": "방문종료일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "방문 종료일"},
            {"physical_name": "visit_source_value", "business_name": "방문원본유형", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "원본 방문 유형"},
        ],
    },
    {
        "physical_name": "drug_exposure",
        "business_name": "약물처방",
        "description": "약물 처방 기록 (13,799건). drug_source_value에 원본 약물 코드 저장.",
        "domain": "처방",
        "columns": [
            {"physical_name": "drug_exposure_id", "business_name": "약물처방ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "약물 처방 고유 ID"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "환자 ID (FK → person)"},
            {"physical_name": "drug_concept_id", "business_name": "약물개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "약물 개념 ID"},
            {"physical_name": "drug_exposure_start_date", "business_name": "처방시작일", "data_type": "DATE", "is_pk": False, "is_nullable": False, "description": "처방 시작일"},
            {"physical_name": "drug_exposure_end_date", "business_name": "처방종료일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "처방 종료일"},
            {"physical_name": "drug_source_value", "business_name": "약물원본코드", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "원본 약물 코드"},
        ],
    },
    {
        "physical_name": "measurement",
        "business_name": "검사결과",
        "description": "임상 검사 결과 (170,043건). value_as_number에 수치 결과, unit_source_value에 단위.",
        "domain": "검사",
        "columns": [
            {"physical_name": "measurement_id", "business_name": "검사결과ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "검사 결과 고유 ID"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "환자 ID (FK → person)"},
            {"physical_name": "measurement_concept_id", "business_name": "검사개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "검사 개념 ID"},
            {"physical_name": "measurement_date", "business_name": "검사일", "data_type": "DATE", "is_pk": False, "is_nullable": False, "description": "검사 일자"},
            {"physical_name": "value_as_number", "business_name": "결과값", "data_type": "NUMERIC", "is_pk": False, "is_nullable": True, "description": "검사 결과값 (숫자)"},
            {"physical_name": "value_as_concept_id", "business_name": "결과개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "검사 결과값 (개념)"},
            {"physical_name": "unit_source_value", "business_name": "결과단위", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "결과 단위"},
            {"physical_name": "measurement_source_value", "business_name": "검사원본코드", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "원본 검사 코드"},
        ],
    },
    {
        "physical_name": "observation",
        "business_name": "관찰기록",
        "description": "환자 관찰/관측 기록 (7,899건). 사회력, 알레르기, 기타 임상 관찰.",
        "domain": "관찰",
        "columns": [
            {"physical_name": "observation_id", "business_name": "관찰기록ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "관찰 기록 고유 ID"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "환자 ID (FK → person)"},
            {"physical_name": "observation_concept_id", "business_name": "관찰개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "관찰 개념 ID"},
            {"physical_name": "observation_date", "business_name": "관찰일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "관찰 일자"},
            {"physical_name": "observation_type_concept_id", "business_name": "관찰유형ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "관찰 유형 개념 ID"},
            {"physical_name": "value_as_number", "business_name": "결과값숫자", "data_type": "NUMERIC", "is_pk": False, "is_nullable": True, "description": "관찰 결과값 (숫자)"},
            {"physical_name": "value_as_string", "business_name": "결과값문자", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "관찰 결과값 (문자)"},
            {"physical_name": "observation_source_value", "business_name": "관찰원본코드", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "원본 관찰 코드"},
            {"physical_name": "visit_occurrence_id", "business_name": "방문ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "방문 ID (FK → visit_occurrence)"},
        ],
    },
    {
        "physical_name": "procedure_occurrence",
        "business_name": "시술기록",
        "description": "시술/수술 기록 (17,333건). procedure_source_value에 원본 시술 코드.",
        "domain": "시술",
        "columns": [
            {"physical_name": "procedure_occurrence_id", "business_name": "시술기록ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "시술 기록 고유 ID"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "환자 ID (FK → person)"},
            {"physical_name": "procedure_concept_id", "business_name": "시술개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "시술 개념 ID"},
            {"physical_name": "procedure_date", "business_name": "시술일", "data_type": "DATE", "is_pk": False, "is_nullable": False, "description": "시술 일자"},
            {"physical_name": "procedure_source_value", "business_name": "시술원본코드", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "원본 시술 코드"},
            {"physical_name": "visit_occurrence_id", "business_name": "방문ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "방문 ID (FK → visit_occurrence)"},
        ],
    },
    {
        "physical_name": "imaging_study",
        "business_name": "흉부X-ray영상",
        "description": "NIH Chest X-ray 흉부 영상 데이터 (112,120건). finding_labels는 영문으로 저장됨.",
        "domain": "영상",
        "columns": [
            {"physical_name": "imaging_study_id", "business_name": "영상ID", "data_type": "SERIAL", "is_pk": True, "is_nullable": False, "description": "영상 고유 식별번호"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "INTEGER", "is_pk": False, "is_nullable": True, "description": "환자 ID (FK → person)"},
            {"physical_name": "image_filename", "business_name": "이미지파일명", "data_type": "VARCHAR(200)", "is_pk": False, "is_nullable": True, "description": "PNG 이미지 파일명"},
            {"physical_name": "finding_labels", "business_name": "소견", "data_type": "VARCHAR(500)", "is_pk": False, "is_nullable": True, "description": "영문 소견 라벨 (Pneumonia, Cardiomegaly 등). 복수 소견은 | 구분."},
            {"physical_name": "view_position", "business_name": "촬영방향", "data_type": "VARCHAR(10)", "is_pk": False, "is_nullable": True, "description": "PA(후전면) 또는 AP(전후면)"},
            {"physical_name": "patient_age", "business_name": "환자나이", "data_type": "INTEGER", "is_pk": False, "is_nullable": True, "description": "촬영 시 환자 나이"},
            {"physical_name": "patient_gender", "business_name": "환자성별", "data_type": "VARCHAR(2)", "is_pk": False, "is_nullable": True, "description": "M: 남성, F: 여성"},
            {"physical_name": "image_url", "business_name": "이미지URL", "data_type": "VARCHAR(500)", "is_pk": False, "is_nullable": True, "description": "이미지 API 경로 (/api/v1/imaging/images/파일명.png)"},
        ],
    },
    {
        "physical_name": "cost",
        "business_name": "비용",
        "description": "의료 비용 기록 (4,426,770건). cost 컬럼에 금액, incurred_date에 발생일. person_person_id로 환자 JOIN.",
        "domain": "비용",
        "columns": [
            {"physical_name": "cost_id", "business_name": "비용ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "비용 기록 고유 ID"},
            {"physical_name": "cost_event_id", "business_name": "이벤트ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "비용 발생 이벤트 ID"},
            {"physical_name": "cost", "business_name": "비용금액", "data_type": "DOUBLE PRECISION", "is_pk": False, "is_nullable": True, "description": "비용 금액"},
            {"physical_name": "incurred_date", "business_name": "발생일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "비용 발생일"},
            {"physical_name": "paid_date", "business_name": "지급일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "비용 지급일"},
            {"physical_name": "revenue_code_source_value", "business_name": "수익코드", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "수익 코드 원본값"},
            {"physical_name": "drg_source_value", "business_name": "DRG코드", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "DRG 코드 원본값"},
            {"physical_name": "person_person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "환자 ID (FK → person.person_id)"},
            {"physical_name": "payer_plan_period_payer_plan_period_id", "business_name": "보험기간ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "보험기간 ID (FK → payer_plan_period)"},
        ],
    },
    {
        "physical_name": "payer_plan_period",
        "business_name": "보험기간",
        "description": "환자 보험/보장 기간 (2,768,440건). payer_source_value=보험사, plan_source_value=플랜. contract_person_id로 환자 JOIN.",
        "domain": "보험",
        "columns": [
            {"physical_name": "payer_plan_period_id", "business_name": "보험기간ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "보험 기간 고유 ID"},
            {"physical_name": "contract_person_id", "business_name": "계약환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "계약자(환자) ID (FK → person.person_id)"},
            {"physical_name": "payer_plan_period_start_date", "business_name": "보험시작일", "data_type": "DATE", "is_pk": False, "is_nullable": False, "description": "보험 시작일"},
            {"physical_name": "payer_plan_period_end_date", "business_name": "보험종료일", "data_type": "DATE", "is_pk": False, "is_nullable": False, "description": "보험 종료일"},
            {"physical_name": "payer_source_value", "business_name": "보험사", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "보험사명 원본값"},
            {"physical_name": "plan_source_value", "business_name": "보험플랜", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "보험 플랜 원본값"},
            {"physical_name": "person_person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "환자 ID (FK → person.person_id)"},
        ],
    },
    {
        "physical_name": "condition_era",
        "business_name": "진단기간",
        "description": "연속 진단 기간 집계 (2,518,422건). condition_occurrence를 집계하여 동일 진단의 연속 기간 산출.",
        "domain": "진료",
        "columns": [
            {"physical_name": "condition_era_id", "business_name": "진단기간ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "진단 기간 고유 ID"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "환자 ID (FK → person)"},
            {"physical_name": "condition_concept_id", "business_name": "진단개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "진단 SNOMED 개념 ID"},
            {"physical_name": "condition_era_start_date", "business_name": "기간시작일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "진단 기간 시작일"},
            {"physical_name": "condition_era_end_date", "business_name": "기간종료일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "진단 기간 종료일"},
            {"physical_name": "condition_occurrence_count", "business_name": "발생횟수", "data_type": "INTEGER", "is_pk": False, "is_nullable": True, "description": "해당 기간 내 진단 발생 횟수"},
        ],
    },
    {
        "physical_name": "drug_era",
        "business_name": "약물투여기간",
        "description": "연속 약물 투여 기간 집계 (784,287건). drug_exposure를 집계하여 동일 약물의 연속 투여 기간 산출.",
        "domain": "처방",
        "columns": [
            {"physical_name": "drug_era_id", "business_name": "투여기간ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "약물 투여 기간 고유 ID"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "환자 ID (FK → person)"},
            {"physical_name": "drug_concept_id", "business_name": "약물개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "약물 개념 ID"},
            {"physical_name": "drug_era_start_date", "business_name": "투여시작일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "약물 투여 시작일"},
            {"physical_name": "drug_era_end_date", "business_name": "투여종료일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "약물 투여 종료일"},
            {"physical_name": "drug_exposure_count", "business_name": "처방횟수", "data_type": "INTEGER", "is_pk": False, "is_nullable": True, "description": "해당 기간 내 처방 횟수"},
            {"physical_name": "gap_days", "business_name": "중단일수", "data_type": "INTEGER", "is_pk": False, "is_nullable": True, "description": "투여 중단 일수"},
        ],
    },
    {
        "physical_name": "device_exposure",
        "business_name": "의료기기사용",
        "description": "의료기기 사용 기록 (432,867건). device_source_value에 기기코드, quantity에 수량.",
        "domain": "시술",
        "columns": [
            {"physical_name": "device_exposure_id", "business_name": "기기사용ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "의료기기 사용 고유 ID"},
            {"physical_name": "device_concept_id", "business_name": "기기개념ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "기기 개념 ID"},
            {"physical_name": "device_exposure_start_date", "business_name": "사용시작일", "data_type": "DATE", "is_pk": False, "is_nullable": False, "description": "기기 사용 시작일"},
            {"physical_name": "device_exposure_end_date", "business_name": "사용종료일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "기기 사용 종료일"},
            {"physical_name": "quantity", "business_name": "수량", "data_type": "INTEGER", "is_pk": False, "is_nullable": True, "description": "사용 수량"},
            {"physical_name": "device_source_value", "business_name": "기기원본코드", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "기기 원본 코드"},
            {"physical_name": "person_person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "환자 ID (FK → person.person_id)"},
            {"physical_name": "visit_occurrence_visit_occurrence_id", "business_name": "방문ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "방문 ID (FK → visit_occurrence)"},
        ],
    },
    {
        "physical_name": "observation_period",
        "business_name": "관찰기간",
        "description": "환자 관찰/데이터 수집 기간 (76,070건). 환자별 데이터가 존재하는 기간을 나타냄.",
        "domain": "관찰",
        "columns": [
            {"physical_name": "observation_period_id", "business_name": "관찰기간ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "관찰 기간 고유 ID"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "환자 ID (FK → person)"},
            {"physical_name": "observation_period_start_date", "business_name": "관찰시작일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "관찰 시작일"},
            {"physical_name": "observation_period_end_date", "business_name": "관찰종료일", "data_type": "DATE", "is_pk": False, "is_nullable": True, "description": "관찰 종료일"},
            {"physical_name": "period_type_concept_id", "business_name": "기간유형ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "기간 유형 개념 ID"},
        ],
    },
    {
        "physical_name": "visit_detail",
        "business_name": "방문상세",
        "description": "방문 상세 기록 (51,027건). visit_occurrence 하위의 세부 방문 기록. 담당의, 진료소 포함.",
        "domain": "진료",
        "columns": [
            {"physical_name": "visit_detail_id", "business_name": "방문상세ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "방문 상세 고유 ID"},
            {"physical_name": "visit_detail_concept_id", "business_name": "방문상세유형ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "방문 상세 유형 개념 ID"},
            {"physical_name": "visit_detail_start_date", "business_name": "상세시작일", "data_type": "DATE", "is_pk": False, "is_nullable": False, "description": "상세 방문 시작일"},
            {"physical_name": "visit_detail_end_date", "business_name": "상세종료일", "data_type": "DATE", "is_pk": False, "is_nullable": False, "description": "상세 방문 종료일"},
            {"physical_name": "visit_detail_source_value", "business_name": "방문상세원본값", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "방문 상세 원본값"},
            {"physical_name": "person_id", "business_name": "환자ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "환자 ID (FK → person)"},
            {"physical_name": "provider_id", "business_name": "의료진ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "담당 의료진 ID (FK → provider)"},
            {"physical_name": "care_site_id", "business_name": "진료소ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "진료소 ID (FK → care_site)"},
            {"physical_name": "visit_occurrence_id", "business_name": "방문ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "방문 ID (FK → visit_occurrence)"},
        ],
    },
    {
        "physical_name": "provider",
        "business_name": "의료진",
        "description": "의료진 정보 (905,492건). 의사, 간호사 등 진료 제공자. specialty_source_value에 전문과목.",
        "domain": "조직",
        "columns": [
            {"physical_name": "provider_id", "business_name": "의료진ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "의료진 고유 ID"},
            {"physical_name": "provider_name", "business_name": "의료진이름", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "의료진 이름"},
            {"physical_name": "npi", "business_name": "NPI", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "국가 제공자 식별번호"},
            {"physical_name": "specialty_concept_id", "business_name": "전문분야ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": True, "description": "전문 분야 개념 ID"},
            {"physical_name": "specialty_source_value", "business_name": "전문분야", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "전문 분야 원본값 (전문과목)"},
            {"physical_name": "gender_source_value", "business_name": "성별", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "성별 원본값"},
            {"physical_name": "care_site_care_site_id", "business_name": "소속진료소ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "소속 진료소 ID (FK → care_site)"},
        ],
    },
    {
        "physical_name": "care_site",
        "business_name": "진료소",
        "description": "진료소/부서 정보 (7,100건). 병원 내 진료 장소 및 부서.",
        "domain": "조직",
        "columns": [
            {"physical_name": "care_site_id", "business_name": "진료소ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "진료소 고유 ID"},
            {"physical_name": "care_site_name", "business_name": "진료소명", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "진료소 이름"},
            {"physical_name": "place_of_service_concept_id", "business_name": "서비스장소유형ID", "data_type": "INTEGER", "is_pk": False, "is_nullable": False, "description": "서비스 장소 유형 개념 ID"},
            {"physical_name": "care_site_source_value", "business_name": "진료소원본코드", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "진료소 원본 코드"},
            {"physical_name": "location_location_id", "business_name": "위치ID", "data_type": "BIGINT", "is_pk": False, "is_nullable": False, "description": "위치 ID (FK → location)"},
        ],
    },
    {
        "physical_name": "location",
        "business_name": "위치",
        "description": "지리적 위치 정보 (3,787건). 진료소의 물리적 주소 및 좌표.",
        "domain": "조직",
        "columns": [
            {"physical_name": "location_id", "business_name": "위치ID", "data_type": "BIGINT", "is_pk": True, "is_nullable": False, "description": "위치 고유 ID"},
            {"physical_name": "city", "business_name": "도시", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "도시명"},
            {"physical_name": "state", "business_name": "주/도", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "주/도"},
            {"physical_name": "zip", "business_name": "우편번호", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "우편번호"},
            {"physical_name": "county", "business_name": "군/구", "data_type": "VARCHAR", "is_pk": False, "is_nullable": True, "description": "군/구"},
            {"physical_name": "latitude", "business_name": "위도", "data_type": "REAL", "is_pk": False, "is_nullable": True, "description": "위도 좌표"},
            {"physical_name": "longitude", "business_name": "경도", "data_type": "REAL", "is_pk": False, "is_nullable": True, "description": "경도 좌표"},
        ],
    },
]

# OMOP CDM FK 관계
TABLE_RELATIONSHIPS: List[Dict] = [
    {"from_table": "condition_occurrence", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "condition_occurrence", "from_column": "visit_occurrence_id", "to_table": "visit_occurrence", "to_column": "visit_occurrence_id", "relationship": "many-to-one"},
    {"from_table": "visit_occurrence", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "drug_exposure", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "measurement", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "observation", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "observation", "from_column": "visit_occurrence_id", "to_table": "visit_occurrence", "to_column": "visit_occurrence_id", "relationship": "many-to-one"},
    {"from_table": "procedure_occurrence", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "procedure_occurrence", "from_column": "visit_occurrence_id", "to_table": "visit_occurrence", "to_column": "visit_occurrence_id", "relationship": "many-to-one"},
    {"from_table": "imaging_study", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    # 비용
    {"from_table": "cost", "from_column": "person_person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "cost", "from_column": "payer_plan_period_payer_plan_period_id", "to_table": "payer_plan_period", "to_column": "payer_plan_period_id", "relationship": "many-to-one"},
    # 보험
    {"from_table": "payer_plan_period", "from_column": "contract_person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "payer_plan_period", "from_column": "person_person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    # 진단기간/약물기간
    {"from_table": "condition_era", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "drug_era", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    # 의료기기
    {"from_table": "device_exposure", "from_column": "person_person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "device_exposure", "from_column": "visit_occurrence_visit_occurrence_id", "to_table": "visit_occurrence", "to_column": "visit_occurrence_id", "relationship": "many-to-one"},
    # 관찰기간
    {"from_table": "observation_period", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    # 방문상세
    {"from_table": "visit_detail", "from_column": "person_id", "to_table": "person", "to_column": "person_id", "relationship": "many-to-one"},
    {"from_table": "visit_detail", "from_column": "provider_id", "to_table": "provider", "to_column": "provider_id", "relationship": "many-to-one"},
    {"from_table": "visit_detail", "from_column": "care_site_id", "to_table": "care_site", "to_column": "care_site_id", "relationship": "many-to-one"},
    {"from_table": "visit_detail", "from_column": "visit_occurrence_id", "to_table": "visit_occurrence", "to_column": "visit_occurrence_id", "relationship": "many-to-one"},
    # 의료진 → 진료소 → 위치
    {"from_table": "provider", "from_column": "care_site_care_site_id", "to_table": "care_site", "to_column": "care_site_id", "relationship": "many-to-one"},
    {"from_table": "care_site", "from_column": "location_location_id", "to_table": "location", "to_column": "location_id", "relationship": "many-to-one"},
]

# 키워드 → OMOP CDM 테이블 매핑
KEYWORD_TABLE_MAP: Dict[str, List[str]] = {
    # 환자 관련
    "환자": ["person", "condition_occurrence"],
    "환자수": ["person"],
    "환자 수": ["person"],
    "환자목록": ["person"],
    "환자 목록": ["person"],
    "환자정보": ["person"],
    "환자 정보": ["person"],
    "성별": ["person"],
    "나이": ["person"],
    "연령": ["person"],
    # 방문/입원/외래 관련
    "방문": ["visit_occurrence", "person"],
    "입원": ["visit_occurrence", "person"],
    "입원환자": ["visit_occurrence", "person"],
    "입원 환자": ["visit_occurrence", "person"],
    "퇴원": ["visit_occurrence"],
    "퇴원환자": ["visit_occurrence", "person"],
    "외래": ["visit_occurrence", "person"],
    "외래환자": ["visit_occurrence", "person"],
    "외래 환자": ["visit_occurrence", "person"],
    "응급": ["visit_occurrence", "person"],
    # 진단 관련
    "진단": ["condition_occurrence", "person"],
    "진단코드": ["condition_occurrence"],
    "질병": ["condition_occurrence", "person"],
    "당뇨": ["condition_occurrence", "person"],
    "당뇨병": ["condition_occurrence", "person"],
    "고혈압": ["condition_occurrence", "person"],
    "심방세동": ["condition_occurrence", "person"],
    "심근경색": ["condition_occurrence", "person"],
    "뇌졸중": ["condition_occurrence", "person"],
    "기관지염": ["condition_occurrence", "person"],
    "인두염": ["condition_occurrence", "person"],
    # 약물 관련
    "약물": ["drug_exposure", "person"],
    "처방": ["drug_exposure", "person"],
    "투약": ["drug_exposure", "person"],
    "약": ["drug_exposure", "person"],
    # 검사 관련
    "검사": ["measurement", "person"],
    "검사결과": ["measurement"],
    "임상검사": ["measurement"],
    "혈액검사": ["measurement"],
    "Lab": ["measurement"],
    # 관찰 관련
    "관찰": ["observation", "person"],
    # 시술 관련
    "시술": ["procedure_occurrence", "person"],
    "수술": ["procedure_occurrence", "person"],
    # 비용 관련
    "비용": ["cost", "person"],
    "진료비": ["cost", "person"],
    "의료비": ["cost", "person"],
    "청구": ["cost"],
    "DRG": ["cost"],
    "수익": ["cost"],
    # 보험 관련
    "보험": ["payer_plan_period", "person"],
    "보험사": ["payer_plan_period"],
    "보험기간": ["payer_plan_period"],
    "보장": ["payer_plan_period"],
    "플랜": ["payer_plan_period"],
    # 진단기간 관련
    "진단기간": ["condition_era", "person"],
    "질환기간": ["condition_era", "person"],
    "이환기간": ["condition_era", "person"],
    # 약물기간 관련
    "투여기간": ["drug_era", "person"],
    "약물기간": ["drug_era", "person"],
    "복용기간": ["drug_era", "person"],
    # 의료기기 관련
    "기기": ["device_exposure", "person"],
    "의료기기": ["device_exposure", "person"],
    "장치": ["device_exposure", "person"],
    "디바이스": ["device_exposure", "person"],
    # 관찰기간 관련
    "관찰기간": ["observation_period", "person"],
    # 방문상세 관련
    "방문상세": ["visit_detail", "visit_occurrence", "person"],
    "방문 상세": ["visit_detail", "visit_occurrence", "person"],
    # 의료진 관련
    "의사": ["provider", "visit_detail"],
    "의료진": ["provider", "visit_detail"],
    "담당의": ["provider", "visit_detail"],
    "전문과": ["provider"],
    "전문의": ["provider"],
    # 진료소/부서 관련
    "진료소": ["care_site", "provider"],
    "진료과": ["care_site"],
    "부서": ["care_site"],
    "병원": ["care_site", "location"],
    # 위치 관련
    "위치": ["location", "care_site"],
    "주소": ["location"],
    "지역": ["location"],
    # 영상 관련
    "영상": ["imaging_study"],
    "이미지": ["imaging_study"],
    "X-ray": ["imaging_study"],
    "xray": ["imaging_study"],
    "흉부": ["imaging_study"],
    "chest": ["imaging_study"],
    "촬영": ["imaging_study"],
    "방사선": ["imaging_study"],
    "폐렴": ["imaging_study", "condition_occurrence"],
    "심비대": ["imaging_study"],
    "흉수": ["imaging_study"],
    "기흉": ["imaging_study"],
    "폐기종": ["imaging_study"],
    "무기폐": ["imaging_study"],
    "결절": ["imaging_study"],
    "종괴": ["imaging_study"],
    "침윤": ["imaging_study"],
}

# SNOMED CT 코드 매핑 (Synthea OMOP CDM 데이터)
ICD_CODE_MAP: Dict[str, Tuple[str, str]] = {
    # 내분비/대사 질환
    "당뇨": ("44054006", "제2형 당뇨병"),
    "당뇨병": ("44054006", "제2형 당뇨병"),
    "제2형 당뇨병": ("44054006", "제2형 당뇨병"),
    "고혈압": ("38341003", "고혈압성 장애"),
    "혈압": ("38341003", "고혈압성 장애"),
    # 심혈관 질환
    "심방세동": ("49436004", "심방세동"),
    "관상동맥질환": ("53741008", "관상동맥 죽상경화증"),
    "심근경색": ("22298006", "심근경색"),
    "뇌졸중": ("230690007", "뇌졸중"),
    # 호흡기 질환
    "기관지염": ("10509002", "급성 기관지염"),
    "인두염": ("195662009", "급성 바이러스성 인두염"),
}

# 동의어 매핑 (구어체/약어 → 표준 용어)
SYNONYM_MAP: Dict[str, str] = {
    "당뇨환자": "당뇨병 환자",
    "DM": "당뇨병",
    "DM환자": "당뇨병 환자",
    "고혈압환자": "고혈압 환자",
    "HTN": "고혈압",
    "혈압환자": "고혈압 환자",
    "Ca": "암",
    "암환자": "암 환자",
    "입원환자": "입원 환자",
    "입원한 환자": "입원 환자",
    "입원 중인 환자": "입원 환자",
    "퇴원환자": "퇴원 환자",
    "퇴원한 환자": "퇴원 환자",
    "외래환자": "외래 환자",
    "외래 진료 환자": "외래 환자",
    "혈액검사": "임상검사",
    "피검사": "임상검사",
    "Lab": "임상검사",
}
